#!/bin/bash
> temp.h
NEWFILE=""
cat $1 | while read item
do
  if [ "${item}" == "//EOF" ]; then
    echo "${item}" >> temp.h
    break
  else
    echo "${item}" >> temp.h
  fi
done

RADICAL="$(echo ${1} | rev | cut -c 3- | rev)"

FUNC="$(sed ':again;$!N;$!b again; :b; s/{[^{}]*}//g; t b' ${RADICAL}.cpp | sed 's/)/);/g' | tail -n +2)"

echo "${FUNC}" >> temp.h
echo "#endif" >> temp.h

cat temp.h > $1
rm temp.h



